{% set name = "ridgeplot-py" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: afa5eab4f0379f79afcd1e2b13bae91256e98ee0e7c92e4d042699aaa74cce4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
    - poetry-dynamic-versioning
  run:
    - python >=3.7,<4.0
    - matplotlib-base >=3.1.3,<4.0.0
    - more-itertools >=8.9.0,<9.0.0
    - numpy >=1.21.1,<2.0.0
    - scipy >=1.4.1,<2.0.0
    - pandas >=2.0.0

test:
  imports:
    - ridgeplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ridgeplot-py/
  summary: Plotting ridgeplots with matplotlib
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/wckdouglas/ridgeplot-py
  doc_url: https://wckdouglas.github.io/ridgeplot-py/

extra:
  recipe-maintainers:
    - wckdouglas
