{% set name = "ridgeplot-py" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ebc9a1913b17d058e33b90150e8cd8c8aaf62f7f8e79a4dd47e443539651e79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<4.0
    - matplotlib-base >=3.1.3,<4.0.0
    - more-itertools >=8.9.0,<9.0.0
    - numpy >=1.21.1,<2.0.0
    - scipy >=1.4.1,<2.0.0
    - pandas >=2.0.0

test:
  imports:
    - ridgeplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ridgeplot-py/
  summary: Plotting ridgeplots with matplotlib
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/wckdouglas/ridgeplot-py
  doc_url: https://wckdouglas.github.io/ridgeplot-py/

extra:
  recipe-maintainers:
    - wckdouglas
