{% set name = "ridgeplot-py" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ridgeplot-py-{{ version }}.tar.gz
  sha256: a568410edab15bf3065d90dba3c04f18e05dce2f10ab7c99cdb5bd71f0686c07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - matplotlib-base >=3.1.3,<4.0.0
    - more-itertools >=8.9.0,<9.0.0
    - numpy >=1.21.1,<2.0.0
    - scipy >=1.4.1,<2.0.0

test:
  imports:
    - ridgeplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ridgeplot-py/
  summary: Plotting ridgeplots with matplotlib
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wckdouglas
